// This file will be auto-generated by Supabase CLI
// For now, we'll create the basic structure
// Run: npx supabase gen types typescript --project-id your-project-id > lib/supabase/types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string
          username: string
          full_name: string
          avatar_url: string | null
          bio: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username: string
          full_name: string
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          username?: string
          full_name?: string
          avatar_url?: string | null
          bio?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      user_preferences: {
        Row: {
          user_id: string
          dietary_restrictions: string[]
          allergies: string[]
          cuisine_preferences: string[]
          cooking_skill_level: string | null
          household_size: number
          preferred_meal_times: Json
          nutrition_goals: Json
          shopping_preferences: Json
          notification_settings: Json
          updated_at: string
        }
        Insert: {
          user_id: string
          dietary_restrictions?: string[]
          allergies?: string[]
          cuisine_preferences?: string[]
          cooking_skill_level?: string | null
          household_size?: number
          preferred_meal_times?: Json
          nutrition_goals?: Json
          shopping_preferences?: Json
          notification_settings?: Json
          updated_at?: string
        }
        Update: {
          user_id?: string
          dietary_restrictions?: string[]
          allergies?: string[]
          cuisine_preferences?: string[]
          cooking_skill_level?: string | null
          household_size?: number
          preferred_meal_times?: Json
          nutrition_goals?: Json
          shopping_preferences?: Json
          notification_settings?: Json
          updated_at?: string
        }
      }
      ingredients: {
        Row: {
          id: string
          name: string
          plural_name: string | null
          description: string | null
          category: string
          subcategory: string | null
          nutrition: Json
          typical_shelf_life: number | null
          storage_instructions: string | null
          storage_locations: string[]
          typical_package_sizes: Json
          average_price: number | null
          price_unit: string | null
          dietary_flags: string[]
          allergens: string[]
          common_substitutes: string[]
          aliases: string[]
          search_keywords: string[]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          plural_name?: string | null
          description?: string | null
          category: string
          subcategory?: string | null
          nutrition?: Json
          typical_shelf_life?: number | null
          storage_instructions?: string | null
          storage_locations?: string[]
          typical_package_sizes?: Json
          average_price?: number | null
          price_unit?: string | null
          dietary_flags?: string[]
          allergens?: string[]
          common_substitutes?: string[]
          aliases?: string[]
          search_keywords?: string[]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          plural_name?: string | null
          description?: string | null
          category?: string
          subcategory?: string | null
          nutrition?: Json
          typical_shelf_life?: number | null
          storage_instructions?: string | null
          storage_locations?: string[]
          typical_package_sizes?: Json
          average_price?: number | null
          price_unit?: string | null
          dietary_flags?: string[]
          allergens?: string[]
          common_substitutes?: string[]
          aliases?: string[]
          search_keywords?: string[]
          created_at?: string
          updated_at?: string
        }
      }
      recipes: {
        Row: {
          id: string
          name: string
          slug: string
          description: string | null
          image_url: string | null
          video_url: string | null
          prep_time: number
          cook_time: number
          total_time: number
          difficulty: string | null
          servings: number
          serving_size: string | null
          ingredients: Json
          instructions: Json
          equipment: string[]
          tips: string[]
          variations: Json
          nutrition_per_serving: Json
          tags: string[]
          cuisine_types: string[]
          meal_types: string[]
          dietary_info: Json
          season: string[]
          ai_generated: boolean
          ai_generation_params: Json | null
          source_url: string | null
          source_attribution: string | null
          created_by: string | null
          is_public: boolean
          rating_average: number
          rating_count: number
          favorite_count: number
          created_at: string
          updated_at: string
          published_at: string | null
        }
        Insert: {
          id?: string
          name: string
          slug: string
          description?: string | null
          image_url?: string | null
          video_url?: string | null
          prep_time: number
          cook_time: number
          difficulty?: string | null
          servings?: number
          serving_size?: string | null
          ingredients: Json
          instructions: Json
          equipment?: string[]
          tips?: string[]
          variations?: Json
          nutrition_per_serving?: Json
          tags?: string[]
          cuisine_types?: string[]
          meal_types?: string[]
          dietary_info?: Json
          season?: string[]
          ai_generated?: boolean
          ai_generation_params?: Json | null
          source_url?: string | null
          source_attribution?: string | null
          created_by?: string | null
          is_public?: boolean
          rating_average?: number
          rating_count?: number
          favorite_count?: number
          created_at?: string
          updated_at?: string
          published_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          description?: string | null
          image_url?: string | null
          video_url?: string | null
          prep_time?: number
          cook_time?: number
          difficulty?: string | null
          servings?: number
          serving_size?: string | null
          ingredients?: Json
          instructions?: Json
          equipment?: string[]
          tips?: string[]
          variations?: Json
          nutrition_per_serving?: Json
          tags?: string[]
          cuisine_types?: string[]
          meal_types?: string[]
          dietary_info?: Json
          season?: string[]
          ai_generated?: boolean
          ai_generation_params?: Json | null
          source_url?: string | null
          source_attribution?: string | null
          created_by?: string | null
          is_public?: boolean
          rating_average?: number
          rating_count?: number
          favorite_count?: number
          created_at?: string
          updated_at?: string
          published_at?: string | null
        }
      }
      recipe_ratings: {
        Row: {
          id: string
          recipe_id: string
          user_id: string
          rating: number
          review: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          recipe_id: string
          user_id: string
          rating: number
          review?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          recipe_id?: string
          user_id?: string
          rating?: number
          review?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      user_favorites: {
        Row: {
          id: string
          user_id: string
          recipe_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          recipe_id: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          recipe_id?: string
          created_at?: string
        }
      }
      meal_plans: {
        Row: {
          id: string
          user_id: string
          name: string | null
          start_date: string
          end_date: string
          target_calories: number | null
          target_macros: Json | null
          notes: string | null
          is_template: boolean
          is_public: boolean
          template_category: string | null
          created_at: string
          updated_at: string
          last_modified_by: string | null
        }
        Insert: {
          id?: string
          user_id: string
          name?: string | null
          start_date: string
          end_date: string
          target_calories?: number | null
          target_macros?: Json | null
          notes?: string | null
          is_template?: boolean
          is_public?: boolean
          template_category?: string | null
          created_at?: string
          updated_at?: string
          last_modified_by?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          name?: string | null
          start_date?: string
          end_date?: string
          target_calories?: number | null
          target_macros?: Json | null
          notes?: string | null
          is_template?: boolean
          is_public?: boolean
          template_category?: string | null
          created_at?: string
          updated_at?: string
          last_modified_by?: string | null
        }
      }
      planned_meals: {
        Row: {
          id: string
          meal_plan_id: string
          date: string
          meal_type: string
          recipe_id: string | null
          custom_meal: Json | null
          servings: number
          notes: string | null
          is_prepared: boolean
          prepared_at: string | null
          rating: number | null
          feedback: string | null
          planned_prep_time: string | null
          reminder_sent: boolean
          order_index: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          meal_plan_id: string
          date: string
          meal_type: string
          recipe_id?: string | null
          custom_meal?: Json | null
          servings?: number
          notes?: string | null
          is_prepared?: boolean
          prepared_at?: string | null
          rating?: number | null
          feedback?: string | null
          planned_prep_time?: string | null
          reminder_sent?: boolean
          order_index?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          meal_plan_id?: string
          date?: string
          meal_type?: string
          recipe_id?: string | null
          custom_meal?: Json | null
          servings?: number
          notes?: string | null
          is_prepared?: boolean
          prepared_at?: string | null
          rating?: number | null
          feedback?: string | null
          planned_prep_time?: string | null
          reminder_sent?: boolean
          order_index?: number
          created_at?: string
          updated_at?: string
        }
      }
      pantry_items: {
        Row: {
          id: string
          user_id: string
          ingredient_id: string
          quantity: number
          unit: string
          location: string | null
          container_type: string | null
          purchase_date: string | null
          expiration_date: string | null
          opened_date: string | null
          purchase_price: number | null
          purchase_location: string | null
          status: string
          is_running_low: boolean
          notes: string | null
          barcode: string | null
          brand: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          ingredient_id: string
          quantity: number
          unit: string
          location?: string | null
          container_type?: string | null
          purchase_date?: string | null
          expiration_date?: string | null
          opened_date?: string | null
          purchase_price?: number | null
          purchase_location?: string | null
          status?: string
          is_running_low?: boolean
          notes?: string | null
          barcode?: string | null
          brand?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          ingredient_id?: string
          quantity?: number
          unit?: string
          location?: string | null
          container_type?: string | null
          purchase_date?: string | null
          expiration_date?: string | null
          opened_date?: string | null
          purchase_price?: number | null
          purchase_location?: string | null
          status?: string
          is_running_low?: boolean
          notes?: string | null
          barcode?: string | null
          brand?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      pantry_transactions: {
        Row: {
          id: string
          pantry_item_id: string
          user_id: string
          type: string
          quantity: number
          unit: string
          reason: string | null
          related_meal_id: string | null
          timestamp: string
        }
        Insert: {
          id?: string
          pantry_item_id: string
          user_id: string
          type: string
          quantity: number
          unit: string
          reason?: string | null
          related_meal_id?: string | null
          timestamp?: string
        }
        Update: {
          id?: string
          pantry_item_id?: string
          user_id?: string
          type?: string
          quantity?: number
          unit?: string
          reason?: string | null
          related_meal_id?: string | null
          timestamp?: string
        }
      }
      shopping_lists: {
        Row: {
          id: string
          user_id: string
          name: string
          status: string
          planned_shopping_date: string | null
          completed_at: string | null
          meal_plan_ids: string[]
          preferred_store_id: string | null
          estimated_total: number | null
          actual_total: number | null
          shared_with: string[]
          is_collaborative: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          status?: string
          planned_shopping_date?: string | null
          completed_at?: string | null
          meal_plan_ids?: string[]
          preferred_store_id?: string | null
          estimated_total?: number | null
          actual_total?: number | null
          shared_with?: string[]
          is_collaborative?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          status?: string
          planned_shopping_date?: string | null
          completed_at?: string | null
          meal_plan_ids?: string[]
          preferred_store_id?: string | null
          estimated_total?: number | null
          actual_total?: number | null
          shared_with?: string[]
          is_collaborative?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      shopping_items: {
        Row: {
          id: string
          shopping_list_id: string
          ingredient_id: string | null
          custom_item_name: string | null
          quantity: number
          unit: string
          category: string
          aisle: string | null
          is_checked: boolean
          checked_at: string | null
          checked_by: string | null
          estimated_price: number | null
          actual_price: number | null
          source_type: string | null
          source_id: string | null
          recipe_names: string[]
          notes: string | null
          priority: string
          brand_preference: string | null
          order_index: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          shopping_list_id: string
          ingredient_id?: string | null
          custom_item_name?: string | null
          quantity: number
          unit: string
          category: string
          aisle?: string | null
          is_checked?: boolean
          checked_at?: string | null
          checked_by?: string | null
          estimated_price?: number | null
          actual_price?: number | null
          source_type?: string | null
          source_id?: string | null
          recipe_names?: string[]
          notes?: string | null
          priority?: string
          brand_preference?: string | null
          order_index?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          shopping_list_id?: string
          ingredient_id?: string | null
          custom_item_name?: string | null
          quantity?: number
          unit?: string
          category?: string
          aisle?: string | null
          is_checked?: boolean
          checked_at?: string | null
          checked_by?: string | null
          estimated_price?: number | null
          actual_price?: number | null
          source_type?: string | null
          source_id?: string | null
          recipe_names?: string[]
          notes?: string | null
          priority?: string
          brand_preference?: string | null
          order_index?: number
          created_at?: string
          updated_at?: string
        }
      }
      stores: {
        Row: {
          id: string
          name: string
          address: string | null
          phone: string | null
          website: string | null
          store_layout: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          address?: string | null
          phone?: string | null
          website?: string | null
          store_layout?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          address?: string | null
          phone?: string | null
          website?: string | null
          store_layout?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}